name: easy_permissions_manager
description: A robust, JSON-based Flutter permission manager for Android, iOS, and Web. Handles configurations, UI prompts, and native setup automatically.
version: 0.0.2
homepage: https://github.com/greelogix/easy_permissions
repository: https://github.com/greelogix/easy_permissions

topics:
  - permissions
  - flutter
  - android
  - ios
  - setup

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0
  xml: ^6.6.1
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
